version: '3.9'
services:
  mongodb: 
    image: mongo:6.0.13
    container_name: meu-mongo2
    networks:
      - compose-bridge

  rodrigobooks:
    image: santosrodrigo89/app-node:1.0
    container_name: rodrigobooks
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on: 
      - mongodb
networks:
  compose-bridge:
    driver: bridge